---
- hosts: all
  become: true
  tasks:
    - name: Display ansible facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Stop EC2 instances
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] == "Debian"
    
